config/routes.rb
# Match IDs with dots in them
id_pattern = /[^\/]+/

ResqueWeb::Engine.routes.draw do

  ResqueWeb::Plugins.plugins.each do |p|
    mount p::Engine => p.engine_path
  end

  resource  :overview,  :only => [:show], :controller => :overview
  resources :working,   :only => [:index]
  resources :queues,    :only => [:index,:show,:destroy], :constraints => {:id => id_pattern}
  resources :workers,   :only => [:index,:show], :constraints => {:id => id_pattern}
  resources :failures,  :only => [:show,:index,:destroy] do
    member do
      put 'retry'
    end
    collection do
      put 'retry_all'
      delete 'destroy_all'
    end
  end

  get '/stats' => "stats#index"
  get '/stats/:action',     :controller => :stats
  get '/stats/:action/:id', :controller => :stats, :constraints => {:id => id_pattern}, :as => :statistic

  root :to => 'overview#show'

end

app/controllers/resque_web/application_controller.rb
module ResqueWeb
  class ApplicationController < ActionController::Base
    protect_from_forgery
    before_action :set_subtabs, :authorize

    helper :all

    def self.subtabs(*tab_names)
      return defined?(@subtabs) ? @subtabs : [] if tab_names.empty?
      @subtabs = tab_names
    end

    def set_subtabs(subtabs = self.class.subtabs)
      @subtabs = subtabs
    end

    private

    def authorize
      if ENV["RESQUE_WEB_HTTP_BASIC_AUTH_USER"] && ENV["RESQUE_WEB_HTTP_BASIC_AUTH_PASSWORD"]
        authenticate_or_request_with_http_basic {|u, p| u == ENV["RESQUE_WEB_HTTP_BASIC_AUTH_USER"] && p == ENV["RESQUE_WEB_HTTP_BASIC_AUTH_PASSWORD"] }
      end
    end
  end
end

app/controllers/resque_web/failures_controller.rb
module ResqueWeb
  class FailuresController < ApplicationController

    # Display all jobs in the failure queue
    #
    # @param [Hash] params
    # @option params [String] :class filters failures shown by class
    # @option params [String] :queue filters failures shown by failure queue name
    def index
    end

    # remove an individual job from the failure queue
    def destroy
      Resque::Failure.remove(params[:id])
      redirect_to failures_path(redirect_params)
    end

    # destroy all jobs from the failure queue
    def destroy_all
      queue = params[:queue] || 'failed'
      Resque::Failure.clear(queue)
      redirect_to failures_path(redirect_params)
    end

    # retry an individual job from the failure queue
    def retry
      reque_single_job(params[:id])
      redirect_to failures_path(redirect_params)
    end

    # retry all jobs from the failure queue
    def retry_all
      if params[:queue].present? && params[:queue]!="failed"
        Resque::Failure.requeue_queue(params[:queue])
      else
        (Resque::Failure.count-1).downto(0).each { |id| reque_single_job(id) }
      end
      redirect_to failures_path(redirect_params)
    end

    private

    #API agnostic for Resque 2 with duck typing on requeue_and_remove
    def reque_single_job(id)
      if Resque::Failure.respond_to?(:requeue_and_remove)
        Resque::Failure.requeue_and_remove(id)
      else
        Resque::Failure.requeue(id)
        Resque::Failure.remove(id)
      end
    end

    def redirect_params
      {}.tap do |p|
        if params[:queue].present?
          p[:queue] = params[:queue]
        end
      end
    end

  end
end

app/controllers/resque_web/overview_controller.rb
module ResqueWeb
  class OverviewController < ApplicationController
    def show
      render :layout => !request.xhr?, :locals => { :polling => request.xhr? }
    end
  end
end

app/controllers/resque_web/queues_controller.rb
module ResqueWeb
  class QueuesController < ApplicationController

    def index
    end

    def show
      set_subtabs view_context.queue_names
    end

    def destroy
      Resque.remove_queue(params[:id])
      redirect_to queues_path
    end

  end
end

app/controllers/resque_web/stats_controller.rb
module ResqueWeb
  class StatsController < ApplicationController
    subtabs :resque, :redis, :keys

    def index
      redirect_to action: "resque"
    end

    def resque
      respond_to do |format|
        format.html
        format.json { render json: Hash[Resque.info.sort] }
      end
    end

    def redis
      respond_to do |format|
        format.html
        format.json { render json: Hash[Resque.redis.info.sort] }
      end
    end

    def keys
      respond_to do |format|
        format.html do
          if params[:id]
            render 'key'
          else
            render 'keys'
          end
        end
        format.json { render json: Resque.keys.sort }
      end
    end
  end
end

app/controllers/resque_web/workers_controller.rb
module ResqueWeb
  class WorkersController < ApplicationController
    before_action :display_subtabs

    def index
    end

    def show
      if params[:id] && params[:id] != 'all'
        @workers = view_context.worker_hosts[params[:id]].map { |id| Resque::Worker.find(id) }
      else
        @workers = Resque.workers
      end
    end

    private

    def display_subtabs
      set_subtabs view_context.worker_hosts.map(&:first)
    end

  end
end

app/controllers/resque_web/working_controller.rb
module ResqueWeb
  class WorkingController < ApplicationController

    def index
    end

  end
end

app/helpers/resque_web/application_helper.rb
module ResqueWeb
  module ApplicationHelper

    PER_PAGE = 20

    def tabs
      t = {'overview' => ResqueWeb::Engine.app.url_helpers.overview_path,
       'working'  => ResqueWeb::Engine.app.url_helpers.working_index_path,
       'failures' => ResqueWeb::Engine.app.url_helpers.failures_path,
       'queues' => ResqueWeb::Engine.app.url_helpers.queues_path,
       'workers' => ResqueWeb::Engine.app.url_helpers.workers_path,
       'stats' => ResqueWeb::Engine.app.url_helpers.stats_path
      }
      ResqueWeb::Plugins.plugins.each do |p|
        p.tabs.each { |tab| t.merge!(tab) }
      end
      t
    end

    def tab(name,path)
      content_tag :li, link_to(name.capitalize, path), :class => current_tab?(name) ? "active" : nil
    end

    def current_tab
      params[:controller].gsub(/resque_web\//, "#{root_path}")
    end

    def current_tab?(name)
      params[:controller] == name.to_s
    end

    attr_reader :subtabs

    def subtab(name)
      content_tag :li, link_to(name, "#{current_tab}/#{name}"), :class => current_subtab?(name) ? "current" : nil
    end

    def current_subtab?(name)
      params[:id] == name.to_s
    end

    def pagination(options = {})
      start    = options[:start] || 1
      per_page = options[:per_page] || PER_PAGE
      total    = options[:total] || 0
      return if total < per_page

      markup = ""
      if start - per_page >= 0
        markup << link_to(raw("&laquo; less"), params.merge(:start => start - per_page), :class => 'btn less')
      end

      if start + per_page <= total
        markup << link_to(raw("more &raquo;"), params.merge(:start => start + per_page), :class => 'btn more')
      end

      content_tag :p, raw(markup), :class => 'pagination'
    end

    def poll(polling=false)
      if polling
        text = "Last Updated: #{Time.now.strftime("%H:%M:%S")}".html_safe
      else
        text = "<a href='#{h(request.path)}' rel='poll'>Live Poll</a>".html_safe
      end
      content_tag :p, text, :class => 'poll'
    end
  end
end

app/helpers/resque_web/failures_helper.rb
module ResqueWeb
  module FailuresHelper
    def each_failure(&block)
      Resque::Failure.each(failure_start_at, failure_per_page, params[:queue], params[:class], &block)
    end

    def failure_date_format
      "%Y/%m/%d %T %z"
    end

    def multiple_failure_queues?
      @multiple_failure_queues ||= Resque::Failure.queues.size > 1
    end

    def failure_queue
      multiple_failure_queues? ? params[:id] : 'failed'
    end

    def failure_queue_name
      @failure_queue_name ||= params[:queue] ? params[:queue] : 'Failed'
    end

    def failure_size
      @failure_size ||= Resque::Failure.count(params[:id], params[:class])
    end

    def failure_per_page
      @failures_per_page ||= params[:class] ? failure_size : 20
    end

    def failure_start_at
      params[:start].to_i
    end

    def failure_end_at
      if failure_start_at + failure_per_page > failure_size
        failure_size
      else
        failure_start_at + failure_per_page
      end
    end

    def failure_class_counts(queue = params[:id])
      classes = Hash.new(0)
      Resque::Failure.each(0, Resque::Failure.count(queue), queue) do |_, item|
        class_name = item['payload']['class'] if item['payload']
        class_name ||= "nil"
        classes[class_name] += 1
      end
      classes.sort_by { |name,_| name }
    end

    def job_arguments(job)
      return 'nil' unless job['payload']
      Array(job['payload']['args']).map { |arg| arg.inspect }.join("\n")
    end
  end
end

app/helpers/resque_web/overview_helper.rb
module ResqueWeb
  module OverviewHelper
    include QueuesHelper
    include WorkingHelper
  end
end

app/helpers/resque_web/queues_helper.rb
require 'resque/failure/redis_multi_queue'

module ResqueWeb
  module QueuesHelper
    def queues_partial_name
      if Resque::Failure.backend == Resque::Failure::RedisMultiQueue
        'resque_web/queues/queues_advanced'
      else
        'resque_web/queues/queues_basic'
      end
    end

    def queue_names
      Resque.queues.sort_by(&:to_s)
    end

    def queue_start_at
      params[:start].to_i
    end

    def queue_end_at
      if queue_start_at + queue_per_page > queue_size
        queue_size
      else
        queue_start_at + queue_per_page
      end
    end

    def queue_per_page
      20
    end

    def queue_size(queue_name = params[:id])
      Resque.size queue_name
    end

    def queue_jobs
      @queue_jobs ||= Resque.peek(params[:id], queue_start_at, queue_per_page)
    end

    def failed_queue_names
      Resque::Failure.queues.sort_by(&:to_s)
    end

    def failed_queue_name(original_queue_name)
      "#{original_queue_name}_failed"
    end

    def failed_queue_class(queue_name)
      Resque::Failure.count(queue_name).zero? ? "failed" : "failure"
    end

    def failed_queue_size(queue_name)
      Resque::Failure.count(queue_name)
    end

    def failed_queue_info(queue_name)
      failed_queue = failed_queue_name(queue_name)
      size = failed_queue_size(failed_queue)

      if size > 0
        css_class = "badge badge-important"
        badge = link_to(size, failure_path(failed_queue))
      else
        css_class = "badge"
        badge = size.to_s
      end

      raw "<span class=\"#{css_class}\">#{badge}</span>"
    end
  end
end

app/helpers/resque_web/stats_helper.rb
module ResqueWeb
  module StatsHelper
    def resque_info
      Resque.info.sort_by { |i| i[0].to_s }
    end

    def redis_info
      Resque.redis.info.to_a.sort_by { |i| i[0].to_s }
    end

    def redis_key_type(key)
      Resque.redis.type(key)
    end

    def redis_key_size(key)
      # FIXME: there's a potential race in this method if a key is modified
      # "in flight". Not sure how to fix it, unfortunately :(
      case redis_key_type(key)
      when 'none'
        0
      when 'list'
        Resque.redis.llen(key)
      when 'set'
        Resque.redis.scard(key)
      when 'string'
        string = Resque.redis.get(key)
        string ? string.length : 0
      when 'zset'
        Resque.redis.zcard(key)
      end
    end

    def redis_get_array(key, start=0)
      case redis_key_type(key)
      when 'none'
        []
      when 'list'
        Resque.redis.lrange(key, start, start + 20)
      when 'set'
        Resque.redis.smembers(key)[start..(start + 20)]
      when 'string'
        [Resque.redis.get(key)]
      when 'zset'
        Resque.redis.zrange(key, start, start + 20)
      when 'hash'
        Resque.redis.hgetall(key)
      end
    end

    def current_subtab?(name)
      params[:action] == name.to_s
    end
  end
end

app/helpers/resque_web/workers_helper.rb
module ResqueWeb
  module WorkersHelper
    def worker_hosts
      @worker_hosts ||= begin
        hosts = Hash.new { [] }

        Resque.workers.each do |worker|
          host, _ = worker.to_s.split(':')
          hosts[host] += [worker.to_s]
        end

        hosts
      end
    end
  end
end

app/helpers/resque_web/working_helper.rb
module ResqueWeb
  module WorkingHelper
    def workers
      @workers ||= Resque.workers
    end

    def jobs
      @jobs ||= workers.map(&:job)
    end

    def worker_jobs
      @worker_jobs ||= workers.zip(jobs).reject { |w, j| w.idle? || j['queue'].nil? }
    end

    def sorted_worker_jobs
      @sorted_worker_jobs ||= worker_jobs.sort_by { |w, j| j['run_at'] || '' }
    end
  end
end

app/views/resque_web/failures/_failed_job.html.erb
<li>
  <dl>
    <% if job.nil? %>
    <dt>Error</dt>
    <dd>Job <%= id %> could not be parsed; perhaps it contains invalid JSON?</dd>
    <% else %>
    <dt>Worker</dt>
    <dd>
      <%= job['worker'].split(':')[0...2].join(':') %>
      on <b class="label label-info"><%= job['queue'] %></b >
      at <b><span class="time"><%= Time.parse(job['failed_at']).strftime(failure_date_format) %></span></b>

      <% if job['retried_at'] %>
        <div class="retried">
          Retried <b><span class="time"><%= Time.parse(job['retried_at']).strftime(failure_date_format) %></span></b>
          <%= link_to "Remove", failure_path(:queue=>failure_queue,:id=>id), :method => :delete, :class => 'remove', :rel => 'remove' %>
        </div>
      <% else %>
        <div class="controls">
          <%= link_to "Retry", retry_failure_path(:queue=>failure_queue,:id=>id), :method => :put %>
          or
          <%= link_to "Remove", failure_path(:queue=>failure_queue,:id=>id), :method => :delete %>
        </div>
      <% end %>
    </dd>
    <dt>Class</dt>
    <dd>
      <% if job['payload'] && job['payload']['class'] %>
        <%= link_to failures_path(:class=>job['payload']['class'],:queue=>params[:queue]) do %>
          <code><%= job['payload']['class'] %></code>
        <% end %>
      <% else %>
        <code>nil</code>
      <% end %>
    </dd>
    <dt>Arguments</dt>
    <dd><pre><%= job_arguments(job) %></pre></dd>
    <dt>Exception</dt>
    <dd><code><%= job['exception'] %></code></dd>
    <dt>Error</dt>
    <dd class="error">
      <% if job['backtrace'] %>
        <a href="#" class="backtrace"><%= job['error'] %></a>
        <pre style='display:none'><%=h job['backtrace'].join("\n") %></pre>
      <% else %>
        <%=h job['error'] %>
      <% end %>
    </dd>
    <% end %>
  </dl>
  <div class="r">
  </div>
</li>

app/views/resque_web/failures/_overview.html.erb
<table class="table table-bordered" id="failed">
<tbody>
  <tr class="total">
    <td class="queue">Total Failed</td>
    <td class="center"><%= Resque::Failure.count %></td>
  </tr>

  <% Resque::Failure.queues.sort.each do |queue| %>
    <tr>
      <th><%= link_to queue, failure_path(queue), :class => 'label label-info' %></th>
      <th style="width:75px;" class="center"><%= Resque::Failure.count(queue) %></th>
    </tr>

    <% failure_class_counts(queue).each do |klass, count| %>
    <tr id="<%= klass %>">
      <td>
        <%= link_to klass, failure_path(queue, :class => klass), :class => "failed failed_class" %>
      </td>
      <td style="text-align: center;" class="failed<%= (count.to_i > 1000) ? '_many' : '' %>"><%= count %></td>
    </tr>
    <% end %>
  <% end %>
</tbody>
</table>

app/views/resque_web/failures/index.html.erb
<% if multiple_failure_queues? && !params[:queue] %>
  <h1>All Failure Queues</h1>
<% else %>
  <h1>Failed Jobs <%= "on '#{params[:queue]}'" if params[:queue] %> <%= "with class '#{params[:class]}'" if params[:class] %></h1>
<% end %>

<% unless failure_size.zero? %>
  <%= form_tag(destroy_all_failures_path(queue: params[:queue]), method: :delete) do %>
    <%= submit_tag "Clear #{failure_queue_name} Jobs", class: 'btn btn-danger', data: { confirm: "Are you sure you want to clear ALL #{failure_queue_name.downcase} jobs?" } %>
    <% if failure_size > failure_per_page %>
      <%= link_to "Last page &raquo;".html_safe, { start: (failure_size - failure_per_page) }, class: 'btn' %>
    <% end %>
  <% end %>
  <%= form_tag(retry_all_failures_path(queue: params[:queue]), method: :put) do %>
    <%= submit_tag "Retry #{failure_queue_name} Jobs", class: 'btn', data: { confirm: "Are you sure you want to retry ALL #{failure_queue_name.downcase} jobs?" } %>
  <% end %>
<% end %>

<% if multiple_failure_queues? && !params[:queue] %>
  <p class="sub"><b><%= Resque::Failure.queues.size %></b> failure queues total</sub>
  <%= render partial: 'overview' %>
<% else %>
  <p class="sub">Showing <%= failure_start_at %> to <%= failure_end_at %> of <b><%= failure_size %></b> jobs</p>

  <ul class="failed">
    <% each_failure do |id, job| %>
      <%= render partial: 'failed_job', locals: { id: id, job: job } %>
    <% end %>
  </ul>

  <%= pagination(start: failure_start_at, total: failure_size) unless params[:class] %>
<% end %>

app/views/resque_web/failures/show.html.erb
<h1>Failed Jobs <%= "on '#{params[:id]}'" if params[:id] %> <%= "with class '#{params[:class]}'" if params[:class] %></h1>

<% if @jobs.any? %>
  <%= form_tag("/failures/#{params[:id] if params[:id]}", :method => :delete) do %>
    <%= submit_tag "Clear #{params[:id] ? "'#{params[:id]}'" : 'Failed'} Jobs", :confirm => "Are you sure?", :class => 'btn btn-danger' %>
  <% end %>
  <%= form_tag("/failures/#{params[:id] ? params[:id] : "all"}/retry") do %>
    <%= submit_tag "Retry #{params[:id] ? "'#{params[:id]}'" : 'Failed'} Jobs", :class => 'btn' %>
  <% end %>
<% end %>

<p class="sub">Showing <%= failure_start_at %> to <%= failure_end_at %> of <b><%= failure_size %></b> jobs</p>

<ul class="failed">
  <% @jobs.each do |id, job| %>
    <%= render :partial => 'failed_job', :locals => {:id => id, :job => job} %>
  <% end %>
</ul>

<%= pagination :start => failure_start_at, :total => failure_size unless params[:class] %>